baseurl = "https://realmq.com/"
languageCode = "en-us"
title = "RealMQ Homepage"
copyright = "Â© 2023 RealMQ GmbH. All rights reserved."

enableEmoji = true
pygmentsCodeFences = true
pygmentsStyle = "trac"
enableRobotsTXT = true

disableKinds = ["taxonomyTerm"]

